package net.crazyinvestor.ticker_producer_engine.deprecated

import net.crazyinvestor.ticker_producer_engine.dto.bithumb.response.BithumbWSTransactionResponse
import org.springframework.context.ApplicationEvent

class BithumbTransactionEvent(response: BithumbWSTransactionResponse) : ApplicationEvent(response)